# Generated by Django 5.2.17 on 2026-08-07 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("free", "Free-form"),
                            ("symptom", "Symptom"),
                            ("medication", "Medication"),
                            ("appointment", "Appointment"),
                        ],
                        default="free",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("fields", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("pdf", "PDF document")],
                        max_length=8,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notes.healthnote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        default="week",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("summary_text", models.TextField(blank=True)),
                ("daily_lines", models.JSONField(blank=True, default=list)),
                ("model_version", models.CharField(blank=True, max_length=32)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("error", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_notes",
                    models.ManyToManyField(
                        blank=True, related_name="summaries", to="notes.healthnote"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI summaries",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="healthnote",
            index=models.Index(
                fields=["user", "-created_at"], name="notes_healt_user_id_f95c64_idx"
            ),
        ),
    ]
