# Generated by Django 5.2.17 on 2026-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthnote",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
