# Generated by Django 5.2.17 on 2026-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_healthnote_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnote',
            name='note_type',
            field=models.CharField(choices=[('vitals', 'Vitals'), ('free', 'Free-form'), ('symptom', 'Symptom'), ('medication', 'Medication'), ('appointment', 'Appointment')], default='free', max_length=16),
        ),
    ]
